name       : robin-hood-hashing
version    : 3.11.3
release    : 2
source     :
    - https://github.com/martinus/robin-hood-hashing/archive/refs/tags/3.11.3.tar.gz : dcf2b7fa9ef9dd0c67102d94c28e8df3effbe1845e0ed1f31f4772ca5e857fc4
license    : MIT
component  : programming.library
summary    : Fast & memory efficient hashtable based on robin hood hashing for C++
description: |
    Fast & memory efficient hashtable based on robin hood hashing for C++11/14/17/20
patterns   : /usr/include
install    : |
    install -Dm00644 src/include/robin_hood.h $installdir/usr/include/robin_hood.h
