name       : robin-hood-hashing
version    : 3.11.2
release    : 1
source     :
    - https://github.com/martinus/robin-hood-hashing/archive/refs/tags/3.11.2.tar.gz : 148b4fbd4fbb30ba10cc97143dcbe385078801b9c9e329cd477c1ea27477cb73
license    : MIT
component  : programming.library
summary    : Fast & memory efficient hashtable based on robin hood hashing for C++
description: |
    Fast & memory efficient hashtable based on robin hood hashing for C++11/14/17/20
patterns   : /usr/include
install    : |
    install -Dm00644 src/include/robin_hood.h $installdir/usr/include/robin_hood.h
