name       : robin-hood-hashing
version    : 3.11.5
release    : 3
source     :
    - https://github.com/martinus/robin-hood-hashing/archive/refs/tags/3.11.5.tar.gz : 3693e44dda569e9a8b87ce8263f7477b23af448a3c3600c8ab9004fe79c20ad0
license    : MIT
component  : programming.library
summary    : Fast & memory efficient hashtable based on robin hood hashing for C++
description: |
    Fast & memory efficient hashtable based on robin hood hashing for C++11/14/17/20
patterns   : /*
setup      : |
    %cmake -DRH_STANDALONE_PROJECT=OFF .
build      : |
    %make
install    : |
    %make_install
